version: '3.8'

services:
    client_ui:
        container_name: clients_ui
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - 3000:3000

    postgres:
        image: postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: keycloak
            POSTGRES_USER: keycloak
            POSTGRES_PASSWORD: keycloak
        networks:
            - keycloak_net

    keycloak:
        depends_on:
            - postgres
        container_name: keycloak
        environment:
            KEYCLOAK_USER: seccom_user
            KEYCLOAK_PASSWORD: 123qwe
            DB_VENDOR: postgres
            DB_ADDR: postgres
            DB_DATABASE: keycloak
            DB_USER: keycloak
            DB_PASSWORD: keycloak
        image: jboss/keycloak
        ports:
            - "8080:8080"
        restart: unless-stopped
        networks:
            - keycloak_net

networks:
    keycloak_net: