version: "3.8"

services:
  intrusion_management_api:
    container_name: imapi
    build:
      context: ./imapi
    env_file:
      - ./imapi/.env
    ports:
      - "8060:8060"
    volumes:
      - ./imapi:/imapi

  sites_management_api:
    container_name: smapi
    build:
      context: ./smapi
    env_file:
      - ./smapi/.env
    ports:
      - "8050:8050"
    volumes:
      - ./smapi:/smapi

  clients_ui:
    container_name: clients_ui
    build:
      context: ./clientui
    ports:
      - "3000:3000"
    volumes:
      - ./clientui/src:/clientui/src

  mgmt_ui:
    container_name: mgmt_ui
    build:
      context: ./mgmtui
    ports:
      - "3010:3010"
    volumes:
      - ./mgmtui/src:/mgmtui/src

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    networks:
      - keycloak_net

  keycloak:
    depends_on:
      - postgres
    container_name: keycloak
    environment:
      KEYCLOAK_USER: seccom_user
      KEYCLOAK_PASSWORD: 123qwe
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
    image: jboss/keycloak
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./keycloak/realms/export:/tmp/export
    command:
      - "-b 0.0.0.0 -Dkeycloak.import=/tmp/export/Clients_UI-realm.json,/tmp/export/Management_UI-realm.json"
    networks:
      - keycloak_net

  rabbitmq3:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'

networks:
  keycloak_net:
