# Generated by Django 4.1.2 on 2022-10-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intrusion',
            name='name',
        ),
        migrations.AddField(
            model_name='intrusion',
            name='camera_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='intrusion',
            name='intrusion_timestamp',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
