# Generated by Django 3.2.3 on 2022-11-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_alter_alarm_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='clientID',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
