# Generated by Django 4.1.2 on 2022-10-23 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_camera_property_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='property_id',
            field=models.ForeignKey(db_column='property_id', null='False', on_delete=django.db.models.deletion.CASCADE, to='myapi.property'),
            preserve_default='False',
        ),
    ]
