# Generated by Django 4.1.2 on 2022-11-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_property_clientid'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='activated',
            field=models.CharField(choices=[('Activated', 'Activated'), ('Deactivated', 'Deactivated')], default='Deactivated', max_length=11),
        ),
        migrations.AlterField(
            model_name='property',
            name='clientID',
            field=models.CharField(choices=[], default=None, max_length=200),
        ),
    ]
