# Generated by Django 4.1.2 on 2022-10-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_alarm_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='type',
            field=models.CharField(choices=[('Sound', 'Sound'), ('Light', 'Light')], max_length=5),
        ),
    ]
