# Generated by Django 3.2.3 on 2022-12-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_alarm_activated_alter_property_clientid'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='activated',
            field=models.CharField(choices=[('Activated', 'Activated'), ('Deactivated', 'Deactivated')], default='Deactivated', max_length=11),
        ),
    ]
